### PR TITLE
Add messaging dashboards

### PR DESCRIPTION
**Pull request by volovyks**
image

### CODE REVIEW

**Comment by volovyks** [comment]
Added the main loop iteration latency dashboard:
image
@ppca can be useful to check the effect of your in-progress PR.

**Comment by ppca** [comment]
Nice dashboard!

**Comment by volovyks** [comment]
@auto-mausx can I merge this? Do we have auto deploy?

**Comment by auto-mausx** [comment]
We can deploy, I'll see if the auto deploy actually works, since last time it didn't for some reason.

**Review by auto-mausx — APPROVED** [review]

**Review by ChaoticTempest — APPROVED** [review]

**Pull request merged**
